const ContactTypes = {
  FETCH_CONTACTS_PENDING: 'FETCH_CONTACTS_PENDING',
  FETCH_CONTACTS_SUCCESS: 'FETCH_CONTACTS_SUCCESS',
  FETCH_CONTACTS_FAIL: 'FETCH_CONTACTS_FAIL',
  GET_CONTACT: 'GET_CONTACT',
  ADD_CONTACT: 'ADD_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
};
export default ContactTypes;
